### ISSUE TITLE
Doesn't open in vscode

### ISSUE THREAD

**Issue by AnthonyGress** [vivaxy/alfred-open-in-vscode#14]
Installed and set wds, i can command + enter to open in finder but typing enter on repo doesn't do anything. Node v 14.19

**Comment by vivaxy** [comment]
Hi, @AnthonyGress.
It will be helpful to me if you could provide following information.
1. [Screen recorder] Open the debug panel, and try to use Alfred to open in VSCode.
2. [Screenshot] The output in the debug panel.
3. The version of Alfred.
4. The version of [alfred-open-in-vscode](https://github.com/vivaxy/alfred-open-in-vscode) workflow.

P.S. Debug panel can be opened like this:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/4216856/166400741-0d26296e-b6ce-463e-9928-289c00ffd5b2.png">

**Comment by AnthonyGress** [comment]
Hey thanks for replying. Turns out it was actually already requested by someone else and it's already done! I didn't realize how easy it was either after seeing the modifications. Thanks again friend, works great!

**Comment by AnthonyGress** [comment]
Honestly, i ended up using [alfred-repos](https://github.com/deanishe/alfred-repos) which worked out of the box. For me, on macOS 12.3.1 M1 MBA running Alfred 4.6.5 i couldn't get this install using npm and had to use yarn. For whatever reason i still couldn't get this to work.

**Comment by vivaxy** [comment]
@AnthonyGress Thanks for the reply. That's an awesome workflow.
