### ISSUE TITLE
Make wds value permanent

### ISSUE THREAD

**Issue by oleynikandrey** [vivaxy/alfred-open-in-vscode#16]
Environment variables are not permanent and reset on each reboot. It leads to need to constantly set `wds` variable.
May be it's better to move the variable to `User Configuration`, where it should not be reset every reboot?

**Comment by vivaxy** [comment]
@oleynikandrey Environment variables is permanent in alfred. After a system reboot, the environment variables are still there.

I've switched to `User Configuration` in alfred-open-in-vscode@2.0.1. Please try the new version.
